In [ ]:
Q-Table Learning

In [1]:
import gym
import numpy as np

load the environment

In [2]:
env = gym.make('FrozenLake-v0')

In [ ]:
impement q-table learning algorithm

In [17]:
# initialize table with all zeros
Q = np.zeros([env.observation_space.n,env.action_space.n])

# set learning parameters
lr = .8
y = .95
num_episodes = 2000
# create lists to contain total rewards and steps per episode
# jList = []
rList = []
for i in range(num_episodes):
    # reset environment and get first new observation
    s = env.reset()
    rAll = 0
    d = False
    j = 0
    
    # The Q-Table learning algorithm
    while j < 99:
        j += 1
        
        # choose an action from picking greedily (with noise) from Q Table
        a = np.argmax(Q[s,:] + np.random.randn(1,env.action_space.n)*(1./(i+1)))
        # get a new state and reward from environment
        s1,r,d,_ = env.step(a)
        # update Q-Table with new knowledge
        Q[s,a] = Q[s,a] + lr*(r + y*np.max(Q[s1,:]) - Q[s,a])
        rAll += r
        s = s1
        if d == True:
            break
        #jList.append(j)
        rList.append(rAll)

In [18]:
print ("Score over time: " +  str(sum(rList)/num_episodes))

Score over time: 0.0


In [19]:
print ("Final Q-Table Values")
print (Q)

Final Q-Table Values
[[4.85206664e-03 6.49380899e-03 3.03143707e-02 6.65950369e-03]
 [4.09497823e-04 1.24881594e-04 1.77081260e-06 2.74786377e-02]
 [1.59438329e-03 1.27564112e-03 9.33026609e-04 1.36055295e-02]
 [5.31892105e-04 6.73412563e-04 4.91127057e-04 1.05349562e-02]
 [6.96654677e-02 3.72867676e-04 2.89846375e-03 1.79122589e-03]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [3.00253037e-03 1.22670060e-04 1.06086235e-04 5.57138130e-04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [6.37998184e-04 1.16583831e-03 2.55666296e-04 9.20535764e-02]
 [7.39328000e-04 5.18390406e-01 2.47333870e-03 1.84550285e-03]
 [1.56913022e-01 1.06645204e-03 2.26765127e-04 1.43267658e-04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [5.32667769e-03 4.33471947e-03 9.18145396e-01 1.97177666e-03]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 7.52330813e-01]
 [0.00000000e+00 0.00000000e+00 0.

In [16]:
a=[1,2,3,4]
b=a[1,:]
# c=a[i:]
# d=a[:j]
# e=a[:]
print(b)

TypeError: list indices must be integers or slices, not tuple